Adding OWA logo
Open-Website-Alliance/website pull request #1
Opened 2024-06-06 19:19 UTC by JKThor

2024-06-07 06:56 UTC, mabolek requested changes
A small suggestion.

Remember to add the logo to `charter.html` as well.

2024-06-07 06:56 UTC, mabolek commented on index.html
> +                <img class="col-md-1" src="images/logos/OWA logo.png" alt="Open Website Alliance">
I suggest we still keep the organization name in, but in a muted color. I also added an image height for better appearance on mobile screens.

```suggestion
                <img class="me-3" src="images/logos/OWA logo.png" height="80" alt="Open Website Alliance">
                <span class="fs-5 text-muted">Open Website Alliance</span>
```

2024-06-18 21:13 UTC, JKThor commented
> A small suggestion.
> 
> Remember to add the logo to `charter.html` as well.

Made changes

2024-06-19 05:59 UTC, mabolek approved these changes

2024-06-19 06:00 UTC, merged